
DefaultContentLanguage = "ru"
baseURL = "http://bighamster.ru/"
languageCode = "ru"
title = "Bighamster's notes"
# theme = "bighamster"

paginate = 20

disqusShortname = "bighamster"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[related]
  threshold = 0
  includeNewer = false
  toLower = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  dateFormat = "January 2, 2006"
  github = "https://github.com/bighamster"
  copyright = "Copyright (C) 2017-2018, Bighamster. All rights reserved."
